// HERO MOVIES REDUCERS
export const HERO_MOVIE_REQUEST = "HERO_MOVIES_REQUEST"
export const HERO_MOVIE_SUCCESS = "HERO_MOVIES_SUCCESS"
export const HERO_MOVIE_FAIL = "HERO_MOVIES_FAIL"

// TRENDING MOVIES REDUCERS
export const TRENDING_MOVIES_REQUEST = "TRENDING_MOVIES_REQUEST"
export const TRENDING_MOVIES_SUCCESS = "TRENDING_MOVIES_SUCCESS"
export const TRENDING_MOVIES_FAIL = "TRENDING_MOVIES_FAIL"

//TOP RATED MOVIES
export const TOPRATED_MOVIES_REQUEST = "TOPRATED_MOVIES_REQUEST"
export const TOPRATED_MOVIES_SUCCESS = "TOPRATED_MOVIES_SUCCESS"
export const TOPRATED_MOVIES_FAIL = "TOPRATED_MOVIES_FAIL"

//ACTION MOVIES
export const ACTION_MOVIES_REQUEST = "ACTION_MOVIES_REQUEST"
export const ACTION_MOVIES_SUCCESS = "ACTION_MOVIES_SUCCESS"
export const ACTION_MOVIES_FAIL = "ACTION_MOVIES_FAIL"

//COMEDY MOVIES
export const COMEDY_MOVIES_REQUEST = "COMEDY_MOVIES_REQUEST"
export const COMEDY_MOVIES_SUCCESS = "COMEDY_MOVIES_SUCCESS"
export const COMEDY_MOVIES_FAIL = "COMEDY_MOVIES_FAIL"

//ROMANCE MOVIES
export const ROMANCE_MOVIES_REQUEST = "ROMANCE_MOVIES_REQUEST"
export const ROMANCE_MOVIES_SUCCESS = "ROMANCE_MOVIES_SUCCESS"
export const ROMANCE_MOVIES_FAIL = "ROMANCE_MOVIES_FAIL"